### PR TITLE
Use canvas method to draw histogram

### PR DESCRIPTION
**Pull request by fairclothjm**
## Features:
- selected minute is drawn in black
- non-selected minute is drawn in gray
- minute marks for each bin at bottom of canvas
- bin count drawn at the top of each bar
- bin height is scaled to fit within the canvas based on the Max bin count for that dir

## Example 1
screenshot 2020-06-28 at 3 15 23 PM

## Example 2
screenshot 2020-06-28 at 3 37 55 PM

## Example 3
screenshot 2020-06-28 at 3 38 05 PM

## Notes
Tested in Firefox and Chrome. Might need a bit more testing to make sure there are no bugs.

Only 60 bins for now. Maybe will try more bins later. But they take up alot of screen real estate as it is.

### CODE REVIEW

**Comment by Matthias-Wandel** [comment]
Very nice.  I wouldn’t number the bins or how many per bin.  That way the
bins can be just a few pixels wide., but maybe add grid lines for every 10
minutes.  Will look at it later.

**Comment by Matthias-Wandel** [comment]
Just having a quick look at it.
I need to review this change before merging it.  I can clone your master 
branch, but I don't know how to get this branch onto my computer to 
review it.  There doesn't appear to be an option to clone your branch.

------ Original Message ------

**Comment by fairclothjm** [comment]
@Matthias-Wandel 

After cloning my repo do a `git fetch --all` to fetch all branches.

Then do a `git checkout hist` to checkout the branch

I think that should do it

**Comment by fairclothjm** [comment]
Or maybe this if you don't want to clone my repo and just set a remote on your repo:

```
git remote add fairclothjm_imgcomp git@github.com:fairclothjm/imgcomp.git
git fetch fairclothjm_imgcomp --all # fetch all branches
git checkout fairclothjm_imgcomp hist # checkout the `hist` branch from  my repo
```

Maybe that will work?

**Comment by fairclothjm** [comment]
Is this more what you had in mind?

screenshot 2020-06-29 at 8 14 45 AM

Let me know and I can push these changes

**Comment by Matthias-Wandel** [comment]
The background thing is a neat idea for the scale, maybe better than the scale idea I had.
But I already re-worked your code to show minuts only ever 10 minutes and pushed it, but no grid lines.  Your idea eliminates the need for that vertical space for the scale numbers.  I also show the position with a background, based on second of image as opposed to snapped to a bin (but maybe snapping the cursor to a bin is better, not sure)

**Comment by Matthias-Wandel** [comment]
Oh, and I figured how to get your branch.  I cloned your repo then pulled the branch, didn't realize that's how it worked.

**Comment by Matthias-Wandel** [comment]
If you want to change it to use that as scale, that would be nice, but 
please base it on my master head rev.


------ Original Message ------

**Pull request merged**
